version: '3.8'
services:
  db:
    image: mysql:8.0
    container_name: billflow-db
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: billflow_db
    ports:
      - "3307:3306"
    restart: unless-stopped

  backend:
    build: ./backend
    container_name: billflow-backend
    ports:
      - "8081:8081"
    environment:
      - SPRING_DATASOURCE_URL=jdbc:mysql://db:3306/billflow_db?allowPublicKeyRetrieval=true&useSSL=false&createDatabaseIfNotExist=true
      - SPRING_DATASOURCE_USERNAME=root
      - SPRING_DATASOURCE_PASSWORD=root
    depends_on:
      - db

  frontend:
    image: nginx:alpine
    container_name: billflow-frontend
    ports:
      - "80:80"
    volumes:
      - ./frontend:/usr/share/nginx/html
    depends_on:
      - backend